In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

## Задание 1. SVD-разложение 

In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
             [3, -4, 2],
             [1, 6, 5],
             [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)
W

array([[ 0.07,  0.72,  0.69],
       [-0.37,  0.67, -0.65],
       [-0.93, -0.21,  0.31]])

In [4]:
V = W.T

In [5]:
s

array([8.82, 6.14, 2.53])

In [6]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [7]:
print(f'Матрица U:\n{U}')
print(f'Матрица D:\n{D}')
print(f'Матрица V:\n{V}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [11]:
a = np.dot(U, np.dot(D, W))
a

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1.,  0.]])

## Задание 2. Нормы матрицы

In [12]:
print(f'Евклидова норма А: {s[0]}')

Евклидова норма А: 8.824868854820442


In [15]:
print(f'Норма Фробениуса: {np.linalg.norm(s)}')

Норма Фробениуса: 11.045361017187261
