In [1]:
import numpy as np

## Задание 1.б

In [3]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


## Задание 1.в

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


## Задание 4.а

In [9]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{a}')
print(f'Ранг:\n{np.linalg.matrix_rank(a):.0f}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг:
2


## Задание 4.б

In [10]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица:\n{a}')
print(f'Ранг:\n{np.linalg.matrix_rank(a):.0f}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг:
3
