## Задание 5

In [7]:
def multiply(A, B):
    m = len(A)
    k = len(B)
    n = len(B[0])
    C = [[0]*n for i in range(m)]
    for i in range(m):
        for j in range(n):
            x = 0
            for ij in range(k):
                x += A[i][ij] * B[ij][j]
            C[i][j] = x
    return C

In [8]:
A = [[1, -2], [3, 0]]
B = [[4, -1], [0, 5]]
multiply(A, B)


[[4, -11], [12, -3]]

In [9]:
import numpy as np

## Задание 2

In [11]:
a = np.array(A)
b = np.array(B)
c = np.dot(a, b)
c

array([[  4, -11],
       [ 12,  -3]])

In [13]:
c = np.dot(b, a)
c

array([[ 1, -8],
       [15,  0]])

In [14]:
c = a + b
c

array([[ 5, -3],
       [ 3,  5]])

## Задание 3

In [26]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
r = 3*a - 2*b + 4*c
r

array([[ 11,  -5],
       [  9, -12]])

## Задание 4

In [19]:
a = np.array([[4, 1], [5, -2], [2, 3]])
at = a.T
at

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [21]:
c = np.dot(a, at)
c

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [22]:
c = np.dot(at, a)
c

array([[45,  0],
       [ 0, 14]])